permalink:        /post/:title

# Setup
title:            "No Zuo No Die"
description:      "Tim's blog"
url:              http://dbtoo.com
baseurl:          "/"
paginate:         5

author:
  name:           "tim"

 