# Site settings
title: DBtoo | da bai tu
description: "Tim's blog."
url: "http://dbtoo.com"
author:
  name: "Tim"
  url: "http://dbtoo.com"

# Build settings
baseurl: ./ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
